---
# tasks file for nginx-deploy

- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: Enable nginx 
  systemd:
    name: nginx
    enabled: yes
  notify: Restart nginx

- template: 
     src: nginx.conf.j2
     dest: /etc/nginx/nginx.conf
  notify: Restart nginx

